export const COLOR = {
    ROUGE: "#FF0000",
    NOIR: "#222222",
    VERTISH: "#00DD00",
    VERT: "#54ffba",
    JAUNE: "#fff654",
    BLANCHE: "#FFFFFF",
    TALE: "#F05599"
  };
export const RESOURSECOLOR = {
    "E": COLOR.VERT,
    "Q": COLOR.JAUNE,
    "I": COLOR.TALE,
    "V": COLOR.VERTISH,
    "A":"#531CB3",
    "C":"#7149EE",
    "D":"#B054FF1",
    // "E":"#ED4FEF",
    "F":"#ED49AB",
    "G":"#ED4FEF",
    "H":"#B754FF",
    "J":"#7149EE",
    "K":COLOR.BLANCHE,
    "L":COLOR.BLANCHE,
    "M":COLOR.BLANCHE,
    "N":COLOR.BLANCHE,
    "O":COLOR.BLANCHE,
    "P":COLOR.BLANCHE,
    "R":COLOR.BLANCHE,
    "S":COLOR.BLANCHE,
    "T":COLOR.BLANCHE,
    "U":COLOR.BLANCHE,
    "W":COLOR.BLANCHE,
    // "Q":COLOR.BLANCHE,
    "Z":COLOR.BLANCHE,
    // "V":COLOR.BLANCHE,

  }